#include: package:pedantic/analysis_options.yaml
#include: package:effective_dart/analysis_options.yaml
#include: package:flutter/analysis_options_user.yaml
include: package:lint/analysis_options.yaml
